"""State definitions for AutoAnalytics.

Implements a research-grade, structured, typed agent state supporting:
- Tripartite failure handling (Code vs Analysis vs Evidence)
- Privacy-aware execution tiers (STRICT, STANDARD, FULL)
- Verifiable analytical plans and evidence traceability
- Multi-step execution history and analytical memory
"""

from typing import Any, Literal
from typing_extensions import TypedDict


# ── Structured Sub-Models & Types ─────────────────────────────────

PrivacyMode = Literal["STRICT", "STANDARD", "FULL"]

ExecutionOutcome = Literal[
    "SUCCESS",
    "CODE_ERROR",
    "DATA_ERROR",
    "ANALYSIS_ERROR",
    "STATISTICAL_WARNING",
    "INSUFFICIENT_EVIDENCE",
    "TASK_MISMATCH",
]

TaskType = Literal[
    "descriptive",
    "diagnostic",
    "comparative",
    "statistical",
    "predictive",
    "forecasting",
    "classification",
    "clustering",
    "anomaly_detection",
    "recommendation",
    "mixed",
    "general_chat",
]


class TaskSpecification(TypedDict, total=False):
    """Structured representation of a user's analytical task."""
    user_goal: str
    analytical_question: str
    task_type: TaskType
    entities: list[str]
    requested_metrics: list[str]
    constraints: list[str]
    expected_output: str
    is_ambiguous: bool
    clarification_needed: str
    required_analysis_categories: list[str]


class ColumnProfile(TypedDict, total=False):
    """Safe metadata profile for an individual column."""
    name: str
    dtype: str
    semantic_type: str  # numeric, categorical, datetime, identifier, text
    null_count: int
    null_percentage: float
    unique_count: int
    is_unique: bool
    sample_summary: list[str]  # Sanitized values or categorical levels (safe under privacy policy)
    stats: dict[str, float]  # min, max, mean, median, std, q25, q75, iqr


class DataProfile(TypedDict, total=False):
    """Structured data context constructed by the profiler without exposing raw tabular data."""
    dataset_name: str
    dataset_path: str
    row_count: int
    column_count: int
    columns: dict[str, ColumnProfile]
    numeric_columns: list[str]
    categorical_columns: list[str]
    datetime_columns: list[str]
    id_columns: list[str]
    relationships: list[dict[str, Any]]
    semantic_description: str
    date_range: dict[str, str]
    memory_usage_mb: float


class PrivacyConfig(TypedDict, total=False):
    """Privacy configuration defining data exposure boundaries to LLM."""
    mode: PrivacyMode
    allow_sample_values: bool
    allow_raw_errors: bool
    anonymize_identifiers: bool
    differential_privacy_applied: bool
    policy_description: str


class PlanStep(TypedDict, total=False):
    """An individual atomic step in an analytical plan."""
    id: int
    objective: str
    operation: str  # filter, aggregate, correlation, regression, forecast, hypothesis_test, explainability
    required_data: list[str]
    expected_output: str
    depends_on: list[int]
    status: Literal["pending", "running", "completed", "failed", "skipped"]


class AnalyticalPlan(TypedDict, total=False):
    """Multi-step analytical plan generated by the Analytical Planner."""
    goal: str
    strategy: str
    steps: list[PlanStep]
    assumptions: list[str]
    validation_criteria: list[str]


class PlanValidation(TypedDict, total=False):
    """Outcome of Plan Validator checking plan structural and semantic correctness."""
    is_valid: bool
    status: Literal["VALID", "INVALID"]
    reasons: list[str]
    affected_steps: list[int]
    suggested_corrections: list[str]
    checks_passed: list[str]


class ExecutionRecord(TypedDict, total=False):
    """Traceable execution output for an analytical code block."""
    step_id: int
    code: str
    runtime: Literal["python", "sql"]
    stdout: str
    stderr: str
    return_value: Any
    extracted_metrics: dict[str, Any]
    artifacts: dict[str, Any]
    execution_time_ms: float
    success: bool
    error_message: str | None


class ExecutionInspection(TypedDict, total=False):
    """Outcome of the Execution Inspector classifying runtime, logic, or statistical issues."""
    outcome: ExecutionOutcome
    error_type: str | None
    details: str
    suggested_action: Literal[
        "PROCEED",
        "REPAIR_CODE",
        "REPLAN",
        "SUPPLEMENT_EVIDENCE",
        "REVISIT_TASK",
        "HUMAN_INTERVENTION",
    ]
    target_step_id: int | None


class StatisticalSupport(TypedDict, total=False):
    """Formal statistical justification for an analytical claim."""
    test_name: str
    p_value: float | None
    statistic_value: float | None
    confidence_interval: tuple[float, float] | None
    sample_size: int | None
    effect_size: float | None


class EvidenceItem(TypedDict, total=False):
    """Structured evidence item linking an analytical claim to concrete computation."""
    id: str
    claim: str
    metric_name: str
    metric_value: Any
    step_id: int
    code_reference: str
    artifact_id: str | None
    statistical_support: StatisticalSupport | None
    confidence_score: float


class EvidenceValidation(TypedDict, total=False):
    """Validation assessment of whether computed evidence strictly supports the findings."""
    is_grounded: bool
    status: Literal["VALID", "INSUFFICIENT", "CONTRADICTORY", "OVERREACH"]
    supported_claims: list[str]
    unsupported_claims: list[str]
    issues: list[str]
    missing_evidence: list[str]
    suggested_replanning_goals: list[str]


class MemoryExperience(TypedDict, total=False):
    """Structured experience record stored in analytical memory."""
    task_type: str
    dataset_signature: str
    plan_summary: str
    successful_steps: list[str]
    failures_encountered: list[str]
    recovery_strategies: list[str]
    insights_learned: list[str]


class MemoryContext(TypedDict, total=False):
    """Context retrieved from analytical memory to guide planning."""
    retrieved_experiences: list[MemoryExperience]
    relevant_heuristics: list[str]


class FinalReport(TypedDict, total=False):
    """Evidence-grounded final analytical report."""
    direct_answer: str
    key_findings: list[str]
    evidence_table: list[dict[str, Any]]
    methodology_summary: str
    limitations: list[str]
    recommendations: list[str]
    evidence_status: str
    traceability_summary: dict[str, Any]


# ── Main Agent State (AutoAnalyticsState) ──────────────────────────


class AutoAnalyticsState(TypedDict, total=False):
    """Master research-grade state representation for AutoAnalytics.

    Maintains clean separation between:
    - User task and semantic intent
    - Privacy configuration and metadata data profiles (raw data stays local)
    - Analytical plan and plan validation
    - Multi-step execution records and inspection
    - Structured evidence and evidence validation
    - Adaptive replanning telemetry and memory context
    - Final evidence-grounded report
    """

    # 1. Task Definition & User Query
    user_task: str
    task_spec: TaskSpecification
    task_type: TaskType
    task_constraints: list[str]

    # 2. Data Context & Privacy Policy
    data_context: DataProfile
    privacy_mode: PrivacyMode
    privacy_config: PrivacyConfig

    # 3. Analytical Goal & Planning
    analytical_goal: str
    analytical_plan: AnalyticalPlan
    plan_validation: PlanValidation

    # 4. Code & Execution Sandbox
    current_code: str
    execution_history: list[ExecutionRecord]
    current_execution: ExecutionRecord
    execution_error: str | None

    # 5. Inspection & Tripartite Outcome
    inspection_result: ExecutionInspection
    replanning_reason: str | None

    # 6. Evidence & Traceability
    evidence: list[EvidenceItem]
    evidence_validation: EvidenceValidation

    # 7. Memory & Experience Store
    memory_context: MemoryContext

    # 8. Final Report & Observability
    final_report: FinalReport
    chat_response: str
    trace: list[dict[str, Any]]
    iteration_count: int
    max_iterations: int
    resource_usage: dict[str, Any]

    # 9. Human-in-the-Loop
    human_intervention_required: bool
    human_feedback: str | None

    # ── Backward Compatibility with Baseline PipelineState ──────────
    dataset_name: str
    raw_data: dict[str, Any]
    schema_info: dict[str, Any]
    cleaning_report: dict[str, Any]
    cleaned_data: dict[str, Any]
    preprocessing_report: dict[str, Any]
    processed_data: dict[str, Any]
    eda_results: dict[str, Any]
    errors: list[str]
    user_query: str
    db_path: str
    db_schema: dict[str, Any]
    intent: str
    sql_query: str
    sql_result: dict[str, Any]
    sql_retry_count: int
    conversation_history: list[dict[str, str]]
    prediction_results: dict[str, Any]
    xai_results: dict[str, Any]
    insight_results: dict[str, Any]
    recommendation_results: dict[str, Any]


# Alias PipelineState to AutoAnalyticsState for complete backwards compatibility
PipelineState = AutoAnalyticsState
