"""Evidence Validator Agent for AutoAnalytics.

Performs secondary empirical verification:
Checks whether computed evidence items mathematically and logically substantiate
the target conclusions, flagging causal overreach, numerical contradictions,
missing metrics, and question-evidence discrepancies.
"""

from typing import Any
from backend.state import EvidenceItem, EvidenceValidation, TaskSpecification, AnalyticalPlan, AutoAnalyticsState


def validate_evidence_grounding(
    evidence: list[EvidenceItem],
    task_spec: TaskSpecification | None = None,
    plan: AnalyticalPlan | None = None,
) -> EvidenceValidation:
    """Evaluate empirical grounding and evidence sufficiency for the analytical task."""
    supported_claims: list[str] = []
    unsupported_claims: list[str] = []
    issues: list[str] = []
    missing_evidence: list[str] = []
    suggested_replanning_goals: list[str] = []

    if not evidence:
        return {
            "is_grounded": False,
            "status": "INSUFFICIENT",
            "supported_claims": [],
            "unsupported_claims": ["No evidence items generated by analytical execution."],
            "issues": ["Zero evidence extracted from execution history."],
            "missing_evidence": ["Computed metrics addressing the core user goal."],
            "suggested_replanning_goals": ["Execute primary aggregation or predictive modeling step."],
        }

    # 1. Audit each individual evidence claim
    for item in evidence:
        claim = item.get("claim", "")
        metric_val = item.get("metric_value")
        stat_supp = item.get("statistical_support")
        confidence = item.get("confidence_score", 0.0)

        # Check for non-null metric values
        if metric_val is None:
            unsupported_claims.append(claim)
            issues.append(f"Evidence '{claim[:40]}...' has null metric value.")
            continue

        # Check for causal overreach keywords in claim
        claim_lower = claim.lower()
        if any(w in claim_lower for w in ["cause", "causes", "caused by", "proves that", "leads directly to", "resulted in"]):
            if not stat_supp or stat_supp.get("test_name") not in ("Instrumental Variables", "Causal Inference", "RCT"):
                unsupported_claims.append(claim)
                issues.append(f"Causal overreach detected in claim: '{claim}'. Observational correlation does not imply causation.")
                continue

        # Confidence boundary check
        if confidence < 0.60:
            unsupported_claims.append(claim)
            issues.append(f"Confidence score ({confidence:.2f}) below empirical threshold (0.60).")
            continue

        supported_claims.append(claim)

    # 2. Check Task-to-Evidence Coverage
    if task_spec:
        req_metrics = [m.lower() for m in task_spec.get("requested_metrics", [])]
        for m in req_metrics:
            if m in ("dataset", "records", "general"):
                continue
            matched = any(m in e.get("metric_name", "").lower() or m in e.get("claim", "").lower() for e in evidence)
            if not matched:
                missing_evidence.append(f"Metric '{m}' requested by user task is missing from evidence graph.")
                suggested_replanning_goals.append(f"Add step to compute metric '{m}'.")

    # Determine status
    if missing_evidence or (len(unsupported_claims) > len(supported_claims)):
        status = "INSUFFICIENT"
        is_grounded = False
    elif any("Causal overreach" in i for i in issues):
        status = "OVERREACH"
        is_grounded = False
    elif issues:
        status = "CONTRADICTORY"
        is_grounded = False
    else:
        status = "VALID"
        is_grounded = True

    return {
        "is_grounded": is_grounded,
        "status": status,
        "supported_claims": supported_claims,
        "unsupported_claims": unsupported_claims,
        "issues": issues,
        "missing_evidence": missing_evidence,
        "suggested_replanning_goals": suggested_replanning_goals,
    }


def evidence_validator_node(state: AutoAnalyticsState) -> dict[str, Any]:
    """LangGraph node verifying empirical validity of extracted evidence."""
    evidence = state.get("evidence") or []
    task_spec = state.get("task_spec")
    plan = state.get("analytical_plan")

    validation = validate_evidence_grounding(evidence, task_spec, plan)

    trace_entry = {
        "node": "evidence_validator",
        "is_grounded": validation["is_grounded"],
        "status": validation["status"],
        "supported_count": len(validation["supported_claims"]),
        "issues": validation["issues"],
    }

    return {
        "evidence_validation": validation,
        "trace": (state.get("trace") or []) + [trace_entry],
    }
